DROP DATABASE IF EXISTS gosocial CASCADE;
CREATE DATABASE IF NOT EXISTS gosocial;
SET DATABASE = gosocial;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    username VARCHAR NOT NULL UNIQUE
);
